Repository DeveloperAcademy-POSTECH/MC2-Team5-Snooze, pull requests merged in 2023-05, with the labels that each got.

#5 기능없는 온보딩 뷰 제작
  OnJeWa.xcodeproj/project.pbxproj
  OnJeWa/Application/SceneDelegate.swift
  OnJeWa/Presentation/OnboardingScene/View/FirstOnboardingView.swift
  OnJeWa/Presentation/OnboardingScene/View/FourOnboardingView.swift
  OnJeWa/Presentation/OnboardingScene/View/SecondOnboardingView.swift
  OnJeWa/Presentation/OnboardingScene/View/ThirdOnboardingView.swift
  OnJeWa/Presentation/OnboardingScene/ViewController/OnboardingViewController.swift
  OnJeWa/Presentation/OnboardingScene/ViewModel/OnboardingViewModel.swift
Labels: ✨ feature

#6 기능없는 등록 뷰 제작
  OnJeWa.xcodeproj/project.pbxproj
  OnJeWa.xcodeproj/xcuserdata/kimsunghun.xcuserdatad/xcschemes/xcschememanagement.plist
  OnJeWa/Application/SceneDelegate.swift
  OnJeWa/Common/KakaoAddressViewController.swift
  OnJeWa/Domain/Entities/PetType.swift
  OnJeWa/Domain/Entities/Profile.swift
  OnJeWa/Presentation/RegistrationScene/View/ChoosePetTypeView.swift
  OnJeWa/Presentation/RegistrationScene/View/RegisterAddressView.swift
  OnJeWa/Presentation/RegistrationScene/View/SetBackgroundView.swift
  OnJeWa/Presentation/RegistrationScene/View/SetProfileView.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/ChoosePetTypeViewController.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/RegisterAddressViewController.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/SetBackgroundViewController.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/SetProfileViewController.swift
  OnJeWa/Presentation/RegistrationScene/ViewModel/ChoosePetTypeViewModel.swift
  OnJeWa/Presentation/RegistrationScene/ViewModel/RegisterAddressViewModel.swift
  OnJeWa/Presentation/RegistrationScene/ViewModel/SetBackgroundViewModel.swift
  OnJeWa/Presentation/RegistrationScene/ViewModel/SetProfileViewModel.swift
  OnJeWa/Resource/Info.plist
  OnJeWaCore/Package.swift
  OnJeWaCore/Sources/OnJeWaCore/Base/BaseViewModel.swift
  OnJeWaCore/Sources/OnJeWaCore/Base/BaseWebViewController.swift
  OnJeWaUI/Package.swift
  OnJeWaUI/Sources/OnJeWaUI/DropDown/DropDown.swift
  OnJeWaUI/Sources/OnJeWaUI/DropDown/DropDownCell.swift
  OnJeWaUI/Sources/OnJeWaUI/DropDown/DropDownDelegateProxy.swift
  OnJeWaUI/Sources/OnJeWaUI/DropDown/DropDownTableView.swift
  OnJeWaUI/Sources/OnJeWaUI/PageControl/OnJeWaPageControl.swift
  OnJeWaUI/Sources/OnJeWaUI/TextField/OnJeWaTextField.swift
Labels: ✨ feature, 💄 ui

#12 로컬 푸시 알림 로직 제작
  OnJeWa.xcodeproj/project.pbxproj
  OnJeWa/Application/AppDelegate.swift
  OnJeWa/Common/LocalNotificationBuilder.swift
Labels: ✨ feature, ⚙️ setting

#13 UserDefault, Realm Manager Set
  OnJeWa.xcodeproj/project.pbxproj
  OnJeWa.xcodeproj/xcuserdata/kimsunghun.xcuserdatad/xcschemes/xcschememanagement.plist
  OnJeWa/Data/Storage/UserDefaults/UserDefaultsSetting.swift
  OnJeWa/Data/Storage/UserDefaults/UserDefaultsWrapper.swift
  OnJeWa/Domain/Entities/Profile.swift
  OnJeWa/GoogleService-Info.plist
  OnJeWa/Presentation/RegistrationScene/View/RegisterAddressView.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/ChoosePetTypeViewController.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/RegisterAddressViewController.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/SetBackgroundViewController.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/SetProfileViewController.swift
  OnJeWaNetwork/Package.swift
  OnJeWaNetwork/Sources/OnJeWaNetwork/Entity/Profile.swift
  OnJeWaNetwork/Sources/OnJeWaNetwork/Error/RealmError.swift
  OnJeWaNetwork/Sources/OnJeWaNetwork/Realm/RealmManager.swift
Labels: ✨ feature

#19 등록 뷰 디테일 작업 완료
  OnJeWa.xcodeproj/xcuserdata/kimsunghun.xcuserdatad/xcschemes/xcschememanagement.plist
  OnJeWa/Application/SceneDelegate.swift
  OnJeWa/Data/Storage/UserDefaults/UserDefaultsSetting.swift
  OnJeWa/Presentation/RegistrationScene/View/ChoosePetTypeView.swift
  OnJeWa/Presentation/RegistrationScene/View/RegisterAddressView.swift
  OnJeWa/Presentation/RegistrationScene/View/SetBackgroundView.swift
  OnJeWa/Presentation/RegistrationScene/View/SetProfileView.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/ChoosePetTypeViewController.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/RegisterAddressViewController.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/SetBackgroundViewController.swift
  OnJeWa/Presentation/RegistrationScene/ViewController/SetProfileViewController.swift
  OnJeWa/Presentation/RegistrationScene/ViewModel/SetProfileViewModel.swift
  OnJeWa/Resource/Assets.xcassets/Registration/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/catcircle.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/catcircle.imageset/catcircle.svg
  OnJeWa/Resource/Assets.xcassets/Registration/catcircleblack.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/catcircleblack.imageset/catcircleblack.svg
  OnJeWa/Resource/Assets.xcassets/Registration/dogcircle.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/dogcircle.imageset/dogcircle.svg
  OnJeWa/Resource/Assets.xcassets/Registration/dogcircleblack.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/dogcircleblack.imageset/dogcircleblack.svg
  OnJeWa/Resource/Assets.xcassets/Registration/myimage.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/myimage.imageset/myimage.svg
  OnJeWa/Resource/Assets.xcassets/Registration/parcircle.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/parcircle.imageset/parcircle.svg
  OnJeWa/Resource/Assets.xcassets/Registration/parcircleblack.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/parcircleblack.imageset/parcircleblack.svg
  OnJeWa/Resource/Assets.xcassets/Registration/pin.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/pin.imageset/pin.svg
  OnJeWa/Resource/Assets.xcassets/Registration/propileplus.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/propileplus.imageset/propileplus.svg
  OnJeWa/Resource/Assets.xcassets/Registration/rbcircle.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/rbcircle.imageset/rbcircle.svg
  OnJeWa/Resource/Assets.xcassets/Registration/rbcircleblack.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/rbcircleblack.imageset/rbcircleblack.svg
  OnJeWa/Resource/Assets.xcassets/Registration/registBlack.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/registBlack.imageset/Rectangle 372.svg
  OnJeWa/Resource/Assets.xcassets/Registration/registWhite.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/Registration/registWhite.imageset/white.svg
  OnJeWa/Resource/Assets.xcassets/main/backbutton.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/main/backbutton.imageset/backbutton.svg
  OnJeWa/Resource/Assets.xcassets/main/backbutton_white.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/main/backbutton_white.imageset/backbutton_white.svg
  OnJeWaNetwork/Sources/OnJeWaNetwork/Entity/Profile.swift
  OnJeWaUI/Sources/OnJeWaUI/Extensions/UIColor+Extension.swift
  OnJeWaUI/Sources/OnJeWaUI/PageControl/OnJeWaPageControl.swift
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/button.colorset/Contents.json
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/camerabutton.colorset/Contents.json
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/cat.colorset/Contents.json
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/dog.colorset/Contents.json
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/dogselect.colorset/Contents.json
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/loginblack.colorset/Contents.json
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/main.colorset/Contents.json
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/namebackground.colorset/Contents.json
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/parrot.colorset/Contents.json
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/rabbit.colorset/Contents.json
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/slidepoint.colorset/Contents.json
Labels: ♻️ refactor, 💄 ui

#20 온보딩 디테일 뷰 작업완료
  OnJeWa.xcodeproj/project.pbxproj
  OnJeWa/Application/SceneDelegate.swift
  OnJeWa/Presentation/LoginScene/LoginViewController.swift
  OnJeWa/Presentation/OnboardingScene/View/FirstOnboardingView.swift
  OnJeWa/Presentation/OnboardingScene/View/FourOnboardingView.swift
  OnJeWa/Presentation/OnboardingScene/View/SecondOnboardingView.swift
  OnJeWa/Presentation/OnboardingScene/View/ThirdOnboardingView.swift
  OnJeWa/Presentation/OnboardingScene/ViewController/OnboardingViewController.swift
  OnJeWa/Presentation/RegistrationScene/View/SetProfileView.swift
  OnJeWa/Resource/Assets.xcassets/login/Contents.json
  OnJeWa/Resource/Assets.xcassets/login/logo.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/login/logo.imageset/logo.svg
  OnJeWa/Resource/Assets.xcassets/onboarding/Contents.json
  OnJeWa/Resource/Assets.xcassets/onboarding/firstOnboarding.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/onboarding/firstOnboarding.imageset/firstOnboarding.png
  OnJeWa/Resource/Assets.xcassets/onboarding/fourOnboarding.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/onboarding/fourOnboarding.imageset/fourOnboarding.png
  OnJeWa/Resource/Assets.xcassets/onboarding/secondOnboarding.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/onboarding/secondOnboarding.imageset/secondOnboarding.png
  OnJeWa/Resource/Assets.xcassets/onboarding/thirdOnboarding.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/onboarding/thirdOnboarding.imageset/Group22.png
  OnJeWaUI/Sources/OnJeWaUI/PageControl/OnJeWaPageControl.swift
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/gray1.colorset/Contents.json
  OnJeWaUI/Sources/OnJeWaUI/Resource/Assets.xcassets/primary.colorset/Contents.json
Labels: ♻️ refactor, 💄 ui

#21 기능없는 서랍 뷰 제작
  OnJeWa.xcodeproj/project.pbxproj
  OnJeWa.xcodeproj/xcuserdata/kimsunghun.xcuserdatad/xcschemes/xcschememanagement.plist
  OnJeWa/Data/Storage/UserDefaults/UserDefaultsSetting.swift
  OnJeWa/Presentation/DrawerScene/View/MissionAlbumView.swift
  OnJeWa/Presentation/DrawerScene/ViewController/DrawerViewController.swift
  OnJeWa/Resource/Assets.xcassets/drawer/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/catLeft.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/catLeft.imageset/catLeft.svg
  OnJeWa/Resource/Assets.xcassets/drawer/catRight.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/catRight.imageset/catRight.svg
  OnJeWa/Resource/Assets.xcassets/drawer/dogLeft.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/dogLeft.imageset/dogLeft.svg
  OnJeWa/Resource/Assets.xcassets/drawer/dogRight.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/dogRight.imageset/dogRight.svg
  OnJeWa/Resource/Assets.xcassets/drawer/family.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/family.imageset/family.svg
  OnJeWa/Resource/Assets.xcassets/drawer/parrotLeft.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/parrotLeft.imageset/parrotLeft.svg
  OnJeWa/Resource/Assets.xcassets/drawer/parrotRight.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/parrotRight.imageset/parrotRight.svg
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitLeft.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitLeft.imageset/rabbitLeft.svg
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitRight.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitRight.imageset/rabbitRight.svg
Labels: ✨ feature, 💄 ui

#24 통계 뷰 제작
  OnJeWa.xcodeproj/project.pbxproj
  OnJeWa.xcodeproj/xcuserdata/kimsunghun.xcuserdatad/xcschemes/xcschememanagement.plist
  OnJeWa/Presentation/DrawerScene/ViewController/StatisticsViewController.swift
  OnJeWa/Resource/Assets.xcassets/drawer/catLastMonth.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/catLastMonth.imageset/catLastMonth.svg
  OnJeWa/Resource/Assets.xcassets/drawer/catLastMonthBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/catLastMonthBottom.imageset/catLastMonthBottom.svg
  OnJeWa/Resource/Assets.xcassets/drawer/catLastWeek.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/catLastWeek.imageset/catLastWeek.svg
  OnJeWa/Resource/Assets.xcassets/drawer/catLastWeekBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/catLastWeekBottom.imageset/catLastWeekBottom.svg
  OnJeWa/Resource/Assets.xcassets/drawer/catSixMonth.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/catSixMonth.imageset/catSixMonth.svg
  OnJeWa/Resource/Assets.xcassets/drawer/catSixMonthBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/catSixMonthBottom.imageset/catSixMonthBottom.svg
  OnJeWa/Resource/Assets.xcassets/drawer/dogLastMonth.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/dogLastMonth.imageset/dogLastMonth.svg
  OnJeWa/Resource/Assets.xcassets/drawer/dogLastMonthBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/dogLastMonthBottom.imageset/dogLastMonthBottom.svg
  OnJeWa/Resource/Assets.xcassets/drawer/dogLastWeek.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/dogLastWeek.imageset/dogLastWeek.svg
  OnJeWa/Resource/Assets.xcassets/drawer/dogLastWeekBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/dogLastWeekBottom.imageset/dogLastWeekBottom.svg
  OnJeWa/Resource/Assets.xcassets/drawer/dogSixMonth.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/dogSixMonth.imageset/dogSixMonth.svg
  OnJeWa/Resource/Assets.xcassets/drawer/dogSixMonthBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/dogSixMonthBottom.imageset/dogSixMonthBottom.svg
  OnJeWa/Resource/Assets.xcassets/drawer/parrotLastMonth.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/parrotLastMonth.imageset/parrotMonth.svg
  OnJeWa/Resource/Assets.xcassets/drawer/parrotLastMonthBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/parrotLastMonthBottom.imageset/parrotLastMonthBottom.svg
  OnJeWa/Resource/Assets.xcassets/drawer/parrotLastWeek.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/parrotLastWeek.imageset/parrotLast.svg
  OnJeWa/Resource/Assets.xcassets/drawer/parrotLastWeekBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/parrotLastWeekBottom.imageset/parrotLastWeekBottom.svg
  OnJeWa/Resource/Assets.xcassets/drawer/parrotSixMonth.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/parrotSixMonth.imageset/parrotSix.svg
  OnJeWa/Resource/Assets.xcassets/drawer/parrotSixMonthBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/parrotSixMonthBottom.imageset/parrotSixMonthBottom.svg
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitLastMonth.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitLastMonth.imageset/rabbitLastMonth.svg
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitLastMonthBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitLastMonthBottom.imageset/rabbitLastMonthBottom.svg
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitLastWeek.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitLastWeek.imageset/rabbitLastWeek.svg
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitLastWeekBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitLastWeekBottom.imageset/rabbitLastWeekBottom.svg
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitSixMonth.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitSixMonth.imageset/rabbitSixMonth.svg
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitSixMonthBottom.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/drawer/rabbitSixMonthBottom.imageset/rabbitSixMonthBottom.svg
Labels: ✨ feature, 💄 ui

#25 미션 뷰 제작
  OnJeWa.xcodeproj/project.pbxproj
  OnJeWa/Application/SceneDelegate.swift
  OnJeWa/Presentation/DrawerScene/ViewController/MissionViewController.swift
  OnJeWa/Resource/Assets.xcassets/mission/Contents.json
  OnJeWa/Resource/Assets.xcassets/mission/camera.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/mission/camera.imageset/camera.svg
  OnJeWa/Resource/Assets.xcassets/mission/carrotbox.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/mission/carrotbox.imageset/carrot.svg
  OnJeWa/Resource/Assets.xcassets/mission/catcarrots.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/mission/catcarrots.imageset/catcarrots.png
  OnJeWa/Resource/Assets.xcassets/mission/dogcarrots.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/mission/dogcarrots.imageset/dogcarrots.png
  OnJeWa/Resource/Assets.xcassets/mission/parrotcarrots.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/mission/parrotcarrots.imageset/parrotcarrots.png
  OnJeWa/Resource/Assets.xcassets/mission/rabbitcarrots.imageset/Contents.json
  OnJeWa/Resource/Assets.xcassets/mission/rabbitcarrots.imageset/rabbitcarrots.png
  OnJeWa/Resource/Info.plist
Labels: ✨ feature, 💄 ui

#29 알림 모아보기 뷰 완료
  OnJeWa.xcodeproj/project.pbxproj
  OnJeWa/Presentation/NotificationScene/View/NotificationViewCell.swift
  OnJeWa/Presentation/NotificationScene/View/NotificationViewChatCell.swift
  OnJeWa/Presentation/NotificationScene/View/NotificationViewInvitationCell.swift
  OnJeWa/Presentation/NotificationScene/View/NotificationViewMissionCell.swift
  OnJeWa/Presentation/NotificationScene/ViewController/NotificationViewController.swift
  OnJeWa/Presentation/NotificationScene/ViewModel/NotificationViewModel.swift
Labels: ✨ feature, 💄 ui

#36 타임워치 세팅
  OnJeWa.xcodeproj/project.pbxproj
  OnJeWa.xcodeproj/project.xcworkspace/xcuserdata/kimsunghun.xcuserdatad/IDEFindNavigatorScopes.plist
  OnJeWa/Application/SceneDelegate.swift
  OnJeWa/Data/Storage/UserDefaults/UserDefaultsSetting.swift
  OnJeWa/Presentation/DrawerScene/View/MissionAlbumView.swift
  OnJeWa/Presentation/LoginScene/LoginViewController.swift
  OnJeWa/Presentation/MainScene/ViewController/MainViewController.swift
  OnJeWa/Presentation/MainScene/ViewController/TapButtonViewController.swift
Labels: ✨ feature, ♻️ refactor
